<footer>
    <div class="container text-white d-flex align-items-center justify-content-between">
        <a id="logo1" href="#"><img src="http://tyrolium.fr/Contenu/Image/TyroDiscord%20Site.png" alt="logo-tyrodiscord"></a>
        <span>2017-2022 © <a style="color: white" href="http://tyrolium.fr/">TYROLIUM</a><br>Created by Maxime Tournier</span>
        <a href='https://tyrolium.fr/contact.php' class="btn btn-default">Contact</a>
    </div>
</footer>


</div>
